# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/forms/xml/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 10, 141, 71))
        self.label.setText("")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 321, 631))
        self.groupBox.setObjectName("groupBox")
        self.objectComboBox = QtWidgets.QComboBox(self.groupBox)
        self.objectComboBox.setGeometry(QtCore.QRect(10, 30, 291, 31))
        self.objectComboBox.setObjectName("objectComboBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 70, 291, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 21, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 21, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 21, 16))
        self.label_4.setObjectName("label_4")
        self.XspinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.XspinBox.setGeometry(QtCore.QRect(40, 30, 71, 22))
        self.XspinBox.setObjectName("XspinBox")
        self.YspinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.YspinBox.setGeometry(QtCore.QRect(40, 60, 71, 22))
        self.YspinBox.setObjectName("YspinBox")
        self.ZspinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.ZspinBox.setGeometry(QtCore.QRect(40, 90, 71, 22))
        self.ZspinBox.setObjectName("ZspinBox")
        self.XhorizontalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.XhorizontalSlider.setGeometry(QtCore.QRect(120, 30, 160, 22))
        self.XhorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.XhorizontalSlider.setObjectName("XhorizontalSlider")
        self.YhorizontalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.YhorizontalSlider.setGeometry(QtCore.QRect(120, 60, 160, 22))
        self.YhorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.YhorizontalSlider.setObjectName("YhorizontalSlider")
        self.ZhorizontalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.ZhorizontalSlider.setGeometry(QtCore.QRect(120, 90, 160, 22))
        self.ZhorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ZhorizontalSlider.setObjectName("ZhorizontalSlider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Settings"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Transform"))
        self.label_2.setText(_translate("MainWindow", "X"))
        self.label_3.setText(_translate("MainWindow", "Y"))
        self.label_4.setText(_translate("MainWindow", "Z"))
